#!/usr/bin/env bash

dir="${PWD##*/}"
dir="$(tr [A-Z] [a-z] <<< "$dir")"

if [ ! -z $2 ]
then
    user=$2
    docker exec -ti --user ${user} ${dir}_$1_1 bash
else
    user=root
    docker exec -ti ${dir}_$1_1 bash
fi
