App\Entity\Agency:
    properties:
        name:
            - NotBlank:
                message: 'validator.agency.name.notblank'
            # - Length:
            #     min: 3
            #     max: 4
            #     minMessage: "Please use at least 3 chars"
            #     maxMessage: 'validator.agency.name.maxLength'
            # - Regex:
            #     pattern: "/^[A-Za-z]+$/"
            #     message: "Please use only letters"
        address:
            - NotBlank:
                message: 'validator.agency.address.notblank'
        latitude:
            - NotBlank:
                message: 'validator.agency.latitude.notblank'
        longitude:
            - NotBlank:
                message: 'validator.agency.longitude.notblank'
