App\Entity\Agency:
    properties:
        name:
            - NotBlank:
                message: "Le nom de l'agence doit être mentionné"
            # - Length:
            #     min: 3
            #     max: 50
            #     minMessage: "Please use at least 3 chars"
            #     maxMessage: "Please use max 50 chars"
            # - Regex:
            #     pattern: "/^[A-Za-z]+$/"
            #     message: "Please use only letters"
        address:
            - NotBlank:
                message: "L'adresse de l'agence doit être mentionné"
        latitude:
            - NotBlank:
                message: "La coordonée Latitude doit être mentionné"
        longitude:
            - NotBlank:
                message: "La coordonée Longitude doit être mentionné"
