App\Entity\Agency:
    properties:
        name:
            - NotBlank:
                message: 'validator.agency.name.notblank'
            # - Length:
            #     min: 3
            #     max: 4
            #     minMessage: "Please use at least 3 chars"
            #     maxMessage: 'validator.agency.name.maxLength'
            # - Regex:
            #     pattern: "/^[A-Za-z]+$/"
            #     message: "Please use only letters"
        address:
            - NotBlank:
                message: 'validator.agency.address.notblank'
        latitude:
            - NotBlank:
                message: 'validator.agency.latitude.notblank'
            - Regex:
                pattern: "/^([-+]?[0-9]{1,2}[.][0-9]+)$/"
                message: "Invalid latitude data"
            - GreaterThanOrEqual:
                value: -90
                message: "Must be greater than or equal than -90"
            - LessThanOrEqual:
                value: 90
                message: "Must be less than or equal 90"
        longitude:
            - NotBlank:
                message: 'validator.agency.longitude.notblank'
            - Regex:
                pattern: "/^([-+]?[0-9]{1,3}[.][0-9]+)$/"
                message: "Invalid longitude data"
            - GreaterThanOrEqual:
                value: -180
                message: "Must be greater than or equal than -180"
            - LessThanOrEqual:
                value: 180
                message: "Must be less than or equal 180"
