fos_rest:
    param_fetcher_listener: true
    view:
        formats:
            json: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', stop: true }
